export enum statusesActionTypes {
  LOAD_STATUSES_TYPES = "[STATUSES] LOAD_STATUSES_TYPES", // do we need all states types?
  LOAD_STATUSES_TYPES_SUCCESS = "[STATUSES] LOAD_STATUSES_TYPES_SUCCESS", // do we need all states types?
  LOAD_STATUSES_TYPES_ERROR = "[STATUSES] LOAD_STATUSES_TYPES_ERROR", // do we need all states types?
  
  LOAD_STATUS_TYPE_BY_ID = "[STATUSES] LOAD_STATUS_TYPE_BY_ID",
  LOAD_STATUS_TYPE_BY_ID_SUCCESS = "[STATUSES] LOAD_STATUS_TYPE_BY_ID_SUCCESS",
  LOAD_STATUS_TYPE_BY_ID_ERROR = "[STATUSES] LOAD_STATUS_TYPE_BY_ID_ERROR"
}